Models/QuestionnaireModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MeusPedidos.Models
{
    public class QuestionnaireModels
    {
        [Required(ErrorMessage = "Por favor informe seu Nome!")]
        [Display(Name = "Nome")]
        [StringLength(40)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Por favor informe seu Email!")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        
        [RegularExpression("(10)|([0123456789])", ErrorMessage = "O campo Html aceita apenas de 0 a 10!")]
        [Display(Name = "Html")]
        public string Html { get; set; }

        [RegularExpression("(10)|([0123456789])", ErrorMessage = "O campo Css aceita apenas de 0 a 10!")]
        [Display(Name = "Css")]
        public string Css { get; set; }

        [RegularExpression("(10)|([0123456789])", ErrorMessage = "O campo JavaScript aceita apenas de 0 a 10!")]
        [Display(Name = "JavaScript")]
        public string JavaScript { get; set; }

        [RegularExpression("(10)|([0123456789])", ErrorMessage = "O campo Python aceita apenas de 0 a 10!")]
        [Display(Name = "Python")]
        public string Python { get; set; }

        [RegularExpression("(10)|([0123456789])", ErrorMessage = "O campo Django aceita apenas de 0 a 10!")]
        [Display(Name = "Django")]
        public string Django { get; set; }

        [RegularExpression("(10)|([0123456789])", ErrorMessage = "O campo Desenvolvimento iOS aceita apenas de 0 a 10!")]
        [Display(Name = "Desenvolvimento iOS")]
        public string DesIOS { get; set; }

        [RegularExpression("(10)|([0123456789])", ErrorMessage = "O campo Desenvolvimento Android aceita apenas de 0 a 10!")]
        [Display(Name = "Desenvolvimento Android")]
        public string DesAndroid { get; set; }
    }
}

Models/SendEmailModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net.Mail;

namespace MeusPedidos.Models
{
    public class SendEmailModels
    {
        public bool Email(string Name, string Email, string Subject, string Body)
        {
            //Define os dados do e-mail
            string nomeRemetente = "Meus Pedidos";
            string emailRemetente = "contato@meuspedidos.com.br";
            string senha = "senha123abc";

            //Host da porta SMTP
            string SMTP = "smtp.dominio.com.br";

            string emailDestinatario = Email;

            string assuntoMensagem = Subject;
            string conteudoMensagem = Body;

            //Cria objeto com dados do e-mail.
            MailMessage objEmail = new MailMessage();

            //Define o Campo From e ReplyTo do e-mail.
            objEmail.From = new System.Net.Mail.MailAddress(nomeRemetente + "<" + emailRemetente + ">");

            //Define os destinatários do e-mail.
            objEmail.To.Add(emailDestinatario);

            //Define a prioridade do e-mail.
            objEmail.Priority = System.Net.Mail.MailPriority.Normal;

            //Define o formato do e-mail HTML (caso não queira HTML alocar valor false)
            objEmail.IsBodyHtml = true;

            //Define título do e-mail.
            objEmail.Subject = assuntoMensagem;

            //Define o corpo do e-mail.
            objEmail.Body = conteudoMensagem;
            
            //Para evitar problemas de caracteres "estranhos", configuramos o charset para "ISO-8859-1"
            objEmail.SubjectEncoding = System.Text.Encoding.GetEncoding("ISO-8859-1");
            objEmail.BodyEncoding = System.Text.Encoding.GetEncoding("ISO-8859-1");

            //Cria objeto com os dados do SMTP
            System.Net.Mail.SmtpClient objSmtp = new System.Net.Mail.SmtpClient();

            //Alocamos o endereço do host para enviar os e-mails              
            objSmtp.Credentials = new System.Net.NetworkCredential(emailRemetente, senha);
            objSmtp.Host = SMTP;
            objSmtp.Port = 587;

            //Enviamos o e-mail através do método .send()
            try
            {
                objSmtp.Send(objEmail);
                return true;
            }
            catch (Exception)
            {
                return false;
            }
            finally
            {
                //excluímos o objeto de e-mail da memória
                objEmail.Dispose();
            }
        }
    }
}

Controllers/QuestionnaireController.cs
using MeusPedidos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeusPedidos.Controllers
{
    public class QuestionnaireController : Controller
    {
        // GET: Questionnaire
        public ActionResult Index()
        {
            return View();
        }

		Teste BWS
		
        // POST: Questionnaire
        [HttpPost]
        public ActionResult Send(QuestionnaireModels model)
        {
            if (ModelState.IsValid)
            {                
                var html = Convert.ToInt32(model.Html);
                var css = Convert.ToInt32(model.Css);
                var javaScript = Convert.ToInt32(model.JavaScript);
                var python = Convert.ToInt32(model.Python);
                var django = Convert.ToInt32(model.Django);
                var desIOS = Convert.ToInt32(model.DesIOS);
                var desAndroid = Convert.ToInt32(model.DesAndroid);
                var subject = "Obrigado por se candidatar";

                if ((html >= 7 && html <= 10) && (css >= 7 && css <= 10) && (javaScript >= 7 && javaScript <= 10))
                {
                    var sendEmail = new SendEmailModels();
                    var body = "Obrigado por se candidatar, assim que tivermos uma vaga disponível " +
                               "para programador Front - End entraremos em contato";

                    var result = sendEmail.Email(model.Name, model.Email, subject, body);

                }
                if ((python >= 7 && python <= 10) && (django >= 7 && django <= 10))
                {
                    var sendemail = new SendEmailModels();
                    var body = "Obrigado por se candidatar, assim que tivermos uma vaga disponível " +
                               "para programador Back-End entraremos em contato.";

                    var result = sendemail.Email(model.Name, model.Email, subject, body);
                }
                if ((desIOS >= 7 && desIOS <= 10) || (desAndroid >= 7 && desAndroid <= 10))
                {
                    var sendEmail = new SendEmailModels();
                    var body = "Obrigado por se candidatar, assim que tivermos uma vaga disponível " +
                               "para programador Mobile entraremos em contato.";

                    var result = sendEmail.Email(model.Name, model.Email, subject, body);
                }
                else
                {
                    var sendEmail = new SendEmailModels();
                    var body = "Obrigado por se candidatar, assim que tivermos uma vaga disponível " +
                               "para programador entraremos em contato.";

                    var result = sendEmail.Email(model.Name, model.Email, subject, body);
                }                
            }
            
            return View("ThankYou");
        }        
    }
}

Views/Questionnaire/Index.cshtml
@model MeusPedidos.Models.QuestionnaireModels
@{
    ViewBag.Title = "Questionário";
}

@using (Html.BeginForm("Send", "Questionnaire", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="jumbotron text-center">
        <h1>Questionário</h1>
        <p class="lead">
            Vamos realizar uma avaliação de candidatos para a vaga de desenvolvedor.
            Por vafor preencha nosso questionario para participar, obrigado!
        </p>
    </div>
    <hr />

    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="row">
        <div class="col-md-8 col-lg-offset-2">
            <h4>Dados do candidato <strong>(Campos obrigatórios)</strong></h4>
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                </div>
            </div>
            <hr />
            <h4>Avalie seu conhecimento de 0 a 10 nos seguintes itens <strong>(Campos opcionais):</strong></h4>
            <div class="form-group">
                @Html.LabelFor(m => m.Html, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Html, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Css, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Css, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.JavaScript, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.JavaScript, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Python, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Python, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Django, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Django, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.DesIOS, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.DesIOS, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.DesAndroid, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.DesAndroid, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <input type="submit" class="btn btn-large btn-info" value="Enviar" id="button" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/validation.js")
}

Views/Questionnaire/ThankYou.cshtml
@{
    ViewBag.Title = "Obrigado !";
}

<div class="jumbotron text-center">
    <h1>Obrigado!</h1>
    <p class="lead">
        Obrigado por responder ao nosso questionário.
    </p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meus Pedidos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meus Pedidos</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>